spring:
  application:
    name: gtw-quick-prescription
  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: users-redirect
              uri: ${AUTH_SERVICE_URI:http://localhost:8081}/
              predicates:
                - Path=/users/**,/users

            - id: prescription-redirect
              uri: ${PRESCRIPTIONS_SERVICE_URI:http://localhost:8082}/
              predicates:
                - Path=/prescriptions/api/prescriptions

security:
  external-auth:
    validation-url: ${AUTH_SERVICE_URI:http://localhost:8081}/users/api/auth/validate-session
    protected-paths:
      - /prescriptions/**
    excluded-paths:
      - /users/api/auth/login
      - /users/api/auth/register
      - /users/swagger-ui/**
      - /users/v3/api-docs/**
      - /users/v3/api-docs/swagger-config
      - /prescriptions/swagger-ui/**
      - /prescriptions/api-docs/**
      - /prescriptions/api-docs/swagger-config

cors:
  allowed-origins:
    - ${SHELL_ORIGIN:http://localhost:3000}